# sdk configurations
sdk:
  max_wait_block: 3
  rest_endpoint: http://35.238.123.59:80
  cli_endpoint: tcp://35.223.7.2:26657
  # trace, debug, info, warn, error, fatal, panic
  log_level: trace

# app configurations
app:
  daemon_timeout_commit: 2